### ISSUE TITLE
Is the debian install for R17 working correctly?

### ISSUE THREAD

**Issue by RomanShestakov** [garethr/garethr-erlang#6]
I am trying to install R17 but keep getting the following err:

Ign http://binaries.erlang-solutions.com precise InRelease
Hit http://binaries.erlang-solutions.com precise Release.gpg
Hit http://binaries.erlang-solutions.com precise Release
Ign http://binaries.erlang-solutions.com precise/contrib TranslationIndex
Err http://binaries.erlang-solutions.com precise/contrib amd64 Packages
  Unable to connect to binaries.erlang-solutions.com:http:
Err http://binaries.erlang-solutions.com precise/contrib i386 Packages
  Unable to connect to binaries.erlang-solutions.com:http:
Err http://binaries.erlang-solutions.com precise/contrib Translation-en_US
  Unable to connect to binaries.erlang-solutions.com:http:
Err http://binaries.erlang-solutions.com precise/contrib Translation-en
  Unable to connect to binaries.erlang-solutions.com:http:
W: Failed to fetch http://binaries.erlang-solutions.com/debian/dists/precise/contrib/binary-amd64/Packages  Unable to connect to binaries.erlang-solutions.com:http:

W: Failed to fetch http://binaries.erlang-solutions.com/debian/dists/precise/contrib/binary-i386/Packages  Unable to connect to binaries.erlang-solutions.com:http:

W: Failed to fetch http://binaries.erlang-solutions.com/debian/dists/precise/contrib/i18n/Translation-en_US  Unable to connect to binaries.erlang-solutions.com:http:

W: Failed to fetch http://binaries.erlang-solutions.com/debian/dists/precise/contrib/i18n/Translation-en  Unable to connect to binaries.erlang-solutions.com:http:

is anybody else has the same problem?

**Comment by denis-sukhoverkhov** [comment]
I now have the same problem. Several times I tried, the same error flies out. What to do?

**Comment by emhlbmc** [comment]
Same problem +1
